export const GET_ERRORS = 'GET_ERRORS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const GET_ALL_USERNAMES = 'GET_ALL_USERNAMES';
export const GET_PROJECT_USERNAMES = 'GET_PROJECT_USERNAMES';
//Types for Backlog Actions

export const GET_BACKLOG = 'GET_BACKLOG';
export const GET_PROJECT_TASK = 'GET_PROJECT_TASK';
export const DELETE_PROJECT_TASK = 'DELETE_PROJECT_TASK';
export const ADD_COMMENT_TO_PROJECT_TASK = 'ADD_COMMENT_TO_PROJECT_TASK'; 

export const SET_CURRENT_USER = 'SET_CURRENT_USER';


